import { Inter, Karla } from 'next/font/google'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const karla = Karla({
  subsets: ['latin'],
  variable: '--font-karla',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${karla.variable}`}>
        {children}
      </body>
    </html>
  )
}
